### ISSUE TITLE
Lower micro-asteroid density in fields

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#112]
As suggested by @FJonske, a reduction to the frequency of the micro-rocks that spawn dynamically while you're in asteroid fields, so that they screw up your aim less commonly and obnoxiously.
This is a simple change and I'll get around to it, hopefully in the next week or two.

**Comment by IrateRedKite** [comment]
Seems to have been done with d281f26f8f3bcb14dc8e88e3f605b6423c93a432

**Comment by IrateRedKite** [comment]
Closed with f23782d7b9db175e3845bf2a80b2c72ec5ef74b3
