### ISSUE TITLE
Buff PPCs/Lasers

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#118]
Playtesters have noted the PPCs and L Lasers feel unsatisfying and awkward to use, and I tend to agree. Before 0.1 is done I'll be taking a crack at making them feel better, likely by improving their energy efficiency and their handling characteristics.

**Comment by IrateRedKite** [comment]
Done with c6fb562d0682265583ec38edc14e62ba227f5c7c

**Comment by IrateRedKite** [comment]
Closed with f23782d7b9db175e3845bf2a80b2c72ec5ef74b3
