### ISSUE TITLE
Shield bubbles for Mining Ships/others

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#120]
I want to put shields on the Mining Ships/Ludlow and, I think, also on weapons platforms. I'll need help from you @IrateRedKite either in learning how to do this myself or in getting your assistance in getting these made. Ideally if I could learn to do this myself I don't have to pester you every time I want to put a shield on something new.

Putting this reasonably high in priority because it's quite important for balancing these already existing encounters that people are engaging in.

**Comment by IrateRedKite** [comment]
@Beaglerush This requires model work and is a little outside of my wheelhouse so I'm not really sure how to do it. We'd want to talk to Nerva about this one.

**Comment by IrateRedKite** [comment]
@Beaglerush Are you happy we've got the shield bubbles we want for 0.1? If so I can set this to close next time we merge

**Comment by IrateRedKite** [comment]
Closed with f23782d7b9db175e3845bf2a80b2c72ec5ef74b3
