### ISSUE TITLE
Improved freighter explosions

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#124]
We have at our disposal some improved explosion effects thanks to why485's FX pack. I'd like to employ some before 0.1 finishes in order to make our freighter kills in particular be cooler.

**Comment by IrateRedKite** [comment]
I think we can do better tbh. Happy to scope new ship explosions for 0.1 as it's some content I can work on.

**Comment by IrateRedKite** [comment]
Implemented with 4b82931d7ca3aa00a21ac3673e7871f8f1a9fa90
