### ISSUE TITLE
Sheet fault when creating Shields file

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#164]
When bmod_equip_shield.ini is generated it's messing up the relation of the shield_type lines to their intended entries. It seems like the shield_types are being offset to the wrong shields by 1. 
We have to discard bmod_equip_shield every time we build right now due to this problem.

**Comment by IrateRedKite** [comment]
This should be fixed! There was a misaligned column in bm_sh_eq.ini.
