### ISSUE TITLE
Feature Request: Max Bank Angle increase

### ISSUE THREAD

**Issue by FJonske** [better-modernized-combat/bmod-client#17]
As per title, I'd like to go from

30/30/30/0 -> 50/40/30/0
for the LF/HF/VH/F, respectively.

It shouldn't change the flying too much, but definitely evokes more of the sudden death 1-circle "I am Galm 1" feeling.

idk, something to consider for the future

**Comment by IrateRedKite** [comment]
I like the idea of this but would like to check if it impacts NPC flight behaviour. Will have a play with these numbers in the next few days and see how things feel.

**Comment by FJonske** [comment]
I'll test this once the balance passes for NPC stats and gear are done. Once those feel right, I'll see if adding banking angle to lights or mediums actually changes enemy (or own) flight patterns.

**Comment by IrateRedKite** [comment]
As this is sort of in the mainstream ship handling stuff now, going to mark this as closed!
