### ISSUE TITLE
Blaster & Shield New Variants Approach

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#23]
Snipped from the DMs of @Fjonske, before it's lost forever:
This is the list for blasters thus far - I was thinking stores should only sell regular variants, and variants are available as immediately warehoused mission rewards, encounter rewards (e.g. via the satellite thingy or when taking down a gunship), or via crafting:

**Increased Damage - XDM**
+10% damage
+10% energy cost
brighter, increased saturation, more base to sound
"This particular piece has been modified to provide increased damage output, at the cost of requiring more energy to fire."

**Increased Refire Rate - XRR**
+10% refire rate
-5% range
+5 energy cost
same video/audio
"This particular piece has been modified to provide an increased refire rate, at the cost of requiring slightly more energy to fire and having slightly decreased range."

**Increased Energy Efficiency - XEE**
-10% energy cost
-15% muzzle velocity
paler, lower saturation
"This particular piece has been modified to provide higher energy efficiency, at the cost of significantly reduced muzzle velocity."

**Increased Muzzle Velocity - XMV**
+20% muzzle velocity
-10% range
same video, more base to sound
"This particular piece has been modified to provide significantly increased muzzle velocity, at the cost of reduced maximum effective range."

**Increased Range - XIR**
+15% range
-5% refire rate
-5% damage
same video/audio
"This particular piece has been modified to provide significantly increased range, at the cost of slightly decreased refire rates and damage output."

**Lostech Variant - XLT**
+5% damage
+5% refire rate
+5% range
+5% muzzle velocity
-5% energy cost
custom video effect, more bass to sound/added reverb
"This particular piece has been produced to extremely high standards and modified extensively, resulting in an all-around better weapon characteristics."

**Poor Quality - XPQ**
-10% damage
-10% range
-10% muzzle velocity
same video, slightly hollow sound
"This particular piece is in a dire state of disrepair and performs poorly compared to its store-brand cousin as a result."
The three letter shorthand would be what I'd add to the nickname to create the variants

Anyway, for shields I did forsake the circular thing, simply because some stats are better than others, and I paired them up instead, like this:

## Component variants - Shields
**Faster Regeneration - XFR**
+10/15%? regeneration rate
+10% energy draw
"This particular unit has been upgraded to provide increased shield regeneration speed, at the cost of increased energy draw."

**Increased Energy Efficiency - XEE**
-15% energy draw
-10% regeneration rate
"This particular unit has been upgraded to consume significantly less energy, at the cost of a noticeable reduction in shield regeneration speed."

**Increased Capacity - XCP**
+15% shield capacity
+20% rebuild time
"This particular unit has been upgraded to be able to take significantly more punishment before shutting down, at the cost of an equally significant increase in rebuild time."

**Increased Rebuild Speed - XRS**
-25% rebuild time
-10% shield capacity
"This particular unit has been upgraded to be able to rebuild blindingly fast for its size, at the cost of a somewhat diminished overall shield capacity."

**Lostech - XLT**
+5% shield regeneration
-5% energy draw
+10% shield capacity
-10% rebuild time
"This particular unit has been produced to extremely high standards and modified extensively, resulting in all-around better characteristics."

**Poor Quality - XPQ**
-10% shield regeneration
-10% shield capacity
+10% rebuild time

"This particular unit is in a dire state of disrepair and performs poorly compared to its store-brand cousin as a result."
regen and energy draw are definitely god stats for shields, so those two are paired, so you can't just improve one with essentially no downside

**Comment by IrateRedKite** [comment]
I've added this to the project tracker unscoped till we can get consensus on these, happy for this to be implemented and tested on a branch, but I suspect individual numbers will need changing. However, as variants go I think these are a fantastic start.

**Comment by FJonske** [comment]
Tried to be more conservative with these, but yes, all of them will get extensive testing, you know my dogfighting addiction. I'll revisit this once the variants get patched in, though, as I'd much rather balance around slightly laggy MP than SP.

**Comment by FJonske** [comment]
- [ ] New Weapon Sheets
- [ ] Variant Blasters Generator
- [ ] Variant Aux Generator
- [ ] Variant Special Equipment (hardcoded)
- [ ] Balance Sanity Checker
- [ ] Automated Infocard Modifier
- [ ] Automated Audio Adjustments
- [ ] Automated Video Adjustments (see ALE generator)

**Comment by IrateRedKite** [comment]
- [ ] https://github.com/better-modernized-combat/bmod-client/issues/34
- [ ] New DLLs to handle gun variant names

**Comment by FJonske** [comment]
As discussed with @IrateRedKite, I'll do a full set of automated variants for aux guns (just a little legwork), but not missiles (ugh). The tl;dr is that missile variants are sort of annoying to set up and would profit immensely in terms of mechanics from a client hook that is still some way into the future.

As a compromise, missiles get a small set of manual variants, if desired.

**Comment by FJonske** [comment]
Given that we can't really have a ton of different ammunitions for every aux gun out there, we've opted to limit aux variants for now, restricting variant rules to stuff that affects the guns and not the ammunition so that they can fire the same kind, i.e. +muzzle velocity or . That said, once Adoxa's ammo switching plugin thingy becomes more accessible, everything is back on the table (e.g. making +ammo with more damage craftable and allowing variant aux guns to fire that ammo).

**Comment by IrateRedKite** [comment]
I think any sort of ammo switching plugin would have to be scoped after 0.1, as it's a client hook. Which variants are we able to do given that we can't compensate w/ reduced lifetime?

**Comment by FJonske** [comment]
The usual ones, minus the increased damage and increased range ones. Anything that touches muzzle velocity also touches range, though, so they're gonna be a little different all around.

**Comment by FJonske** [comment]
This is done now.

For the time being, shields are postponed (and are probably few enough to just do manually), and sfx/vfx have their own issues, as they are their own brand of problem, which may or may not work out, anyway.
