### ISSUE TITLE
Feature Request: ‹‹Scrambled Signal››

### ISSUE THREAD

**Issue by FJonske** [better-modernized-combat/bmod-client#26]
@IrateRedKite We talked about this, you said it was easy to manipulate the infocards on the scanner to scramble those as well.

Somehow, ‹‹Scrambled Signal›› returned.

**Comment by IrateRedKite** [comment]
This is fairly trivial and is just a matter of assigning infocards to use for ships where you want to hide the stats from the player, I've added this to the 0.1 scope, so we can get some infocards assigned for this.

**Comment by FJonske** [comment]
Is in, will close when PR is merged.

**Comment by FJonske** [comment]
Was merged for a while, shows up correctly, closing.
