### ISSUE TITLE
CI/CD Workflow for INI files

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#36]
I'd like to get some basic ini parsing and checking for the CI/CD workflow. Python would be fine for this, as we don't need to parse every single file. Things I'd like to check:

- [x] Any defined paths (da_archetype, item icons, etc) are valid windows paths, and contain no invalid or unnwanted characters
- [x] Any blocks in equipment files that point to other blocks (i.e. gun->munition) are valid
- [x] MarketGood entries point to a valid Good
- [x] Goods point to a valid equipment or commodity
- [x] Encounters in system files point to a working (not just valid) path. 
- [x] Encounters in `[Zone]` blocks correctly reference an `[EncounterParameters]` block
- [x] npcships defined in faction_prop.ini point to a valid npcship in npcships.ini
- [x] Loadouts in npcships.ini point to a valid loadout

These can sort of be hardcoded I think, I'm not too keen to worry too much about Freelancer.ini, as we'll be performing the pipeline on the repository, not a full installation of the game.

**Comment by FJonske** [comment]
Encounters being functional and not just valid could get ugly reeeeeally quickly.

As for other stuff, I'll help out. When should this run? 1) After build, before game launch? 2) Individually, after each component and only for that component? I prefer 1).

**Comment by IrateRedKite** [comment]
I'll defer to your judgement here on what is/isn't a pain to do with any sort of parser we put together!

In terms of when, I was actually thinking of using github workflows for this, so any ini commits would trigger a runner that does checks on whatever's committed and passes/fails accordingly. Workflow is all handled via yaml, but you can almost certainly run arbitrary Python scripts using it.

**Comment by FJonske** [comment]
see PR: https://github.com/better-modernized-combat/bmod-client/pull/50
