### ISSUE TITLE
Fix breaking bug where the game crashes on NPC Death

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#42]
We need to regenerate lootprops with appropriate values for all new non-NPC ammo and guns, as currently the game is crashing at the below offset on NPC death.

```
Time Generated: 2024-02-18 15:57:00
Source Name: Application Error
Event ID: 1000
Exception Code: 0xc0000005
Faulting Application Name: Freelancer.exe, version 0.1.1223.11, PID 16064
Faulting Application Path: C:\Users\Ruper\AppData\Roaming\freelancer-bmod\EXE\Freelancer.exe
Faulting Module Name: Content.dll, version 1.0.1254.11
Faulting Module Path: C:\Users\Ruper\AppData\Roaming\freelancer-bmod\dlls\bin\Content.dll
Fault Offset: 0x000bd173
Attempting to fetch JSON crash information from the Starport KnowledgeBase...
Offset Description: Converts an archID into a goodId and then uses the goodId for a lookup, which fails and is not checked, causing a crash. This occurred when ammo entries for loot were not defined in lootprops.ini. If a munition entry has 'requires_ammo = true', the ammo AND the gun both require a lootprops.ini entry.
Found By: IrateRedKite, Laz & Raikkonen
Date Added: 2024-01-08 16:31:18
```

**Comment by IrateRedKite** [comment]
Review required with c677603ca9a44b50a7992aac78fa9ed0028e4566

**Comment by IrateRedKite** [comment]
Pretty confident, after about 15 minutes of local testing in SP and MP, this is fixed. Closing for now.

**Comment by FJonske** [comment]
New variant generator will automate this by adding everything generated to lootprops inside of a specific block at the bottom of the file.

We cooooould automate this for other stuff as well, if you give me a complete list of where to find that other stuff and whether it already goes through the ini writer at some point.
