### ISSUE TITLE
Determine Status of 'PD Turret' and 'Fleet Energy' Classes

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#44]
Currently there's a bit of crossover here as these fill the same roles. It'd be good to clear this up and figure out how to differentiate them/what the difference actually is.

**Comment by FJonske** [comment]
Here's a thought by @IrateRedKite and myself. Right now, there's sizes for each weapon type (energy/missile/ballistic) for fleet weapons. Realistically, we only need one per type, think "size 4 weapons". In addition to the ST Support (Heal Beam) and PD Turret (3x Turrets, their "regular guns" so to speak) hardpoint types. If we do want smaller weapons, we can always give freighters S/M/L Energy/Ballistic/Missile slots.

Stays: FL Ballistic, FL Energy, FL Missile, PD Turret, ST Support
Dies: FL Ballistic/Energy/Missile S/M/L

**Comment by IrateRedKite** [comment]
I'm all for this, with PD turrets basically taking the role of 'blasters' for larger ships. I think the differentiating factor for these vs 3x is going to be their gimballed nature, with most turrets having way more coverage than their 3x gun counterparts

**Comment by IrateRedKite** [comment]
Decided we're going to go w/ 5 classes and the prefix 'XL' for now for clarity, can change again later, will need to adjust icons

**Comment by IrateRedKite** [comment]
This is nominally done, but I want to test a few things before signing it off. We had a few crashes related to this and the frigate, so I want to make sure it's all good before we confirm things.
