### ISSUE TITLE
Custom Pilot and Bounty Voucher Commodities

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#5]
We currently have bounty vouchers and pilots set up for Xenos, but pilots at least need to be expanded to cover Navy and DSE. These will need unique descriptions and icons, and should be set up with appropriate purchase values on relevant bases. At present no values have been set and any implemented pilots have a value of 1.

- [x] Pilot: Xenos Rookie
- [x] Pilot: Xenos Veteran
- [x] Pilot: Xenos Elite
- [x] Pilot: Xenos Ace
- [x] Pilot: Navy Rookie
- [x] Pilot: Navy Veteran
- [x] Pilot: Navy Elite
- [x] Pilot: Navy Ace
- [x] Pilot: Civilian Rookie
- [x] Pilot: Civilian Veteran
- [x] Pilot: Civilian Elite
- [x] Pilot: Civilian Ace

- [x] Bounty Voucher Xenos Rookie
- [x] Bounty Voucher Xenos Veteran
- [x] Bounty Voucher Xenos Elite
- [x] Bounty Voucher Xenos Ace
- [x] Bounty Voucher Xenos Freighter

We also need a unique icon for the Bounty Voucher, as presently we're using the DRM which isn't the best. I think it's worth having a discussion about whether or not we want to have equivalents to Bounty Vouchers for lawful factions, or take a slightly different approach here.

**Comment by IrateRedKite** [comment]
I have added icons and placeholder infocards for the pilots in 9dc0e33f174e637e0b933092ce322ea3d9e2b4f6 and 7092a7fd041680928710f4ea16605b571375be3b. We only need infocards for the pilots and icons for the bounty vouchers now, in addition to working out the exact economy of these.

**Comment by IrateRedKite** [comment]
These are now in-game and dropping from the correct pilots as of 343b7aa9d1ad257ff9c0dd9356244195f89b2829. Icons still required for bounty vouchers, and we need to confirm the economy for these.

**Comment by IrateRedKite** [comment]
I think physical dogtags would be neat, to differentiate them from unlawfuls. Also sales prices aren't so bad right now, we only have 5 bases!

**Comment by IrateRedKite** [comment]
General tidy-up also needed for equipment items. I've done a few of these, but there's quite a few more missing ones, especially for fleet equipment

**Comment by FJonske** [comment]
I *think* this is done now?

**Comment by IrateRedKite** [comment]
There's a few placeholder descriptions done, but I think these are indeed completed now, do you want to hold off till descriptions are written or are you okay to close?

**Comment by FJonske** [comment]
I'll close this. Anything that should be left rn is a good price tag, and I'd file that under "gets done when economy gets done".
