### ISSUE TITLE
Hardpoint and Balance the Phantom

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#59]

**Comment by FJonske** [comment]
What kind of role are we looking at for this one? Interceptor maybe? Something that travels quickly and stealthily (idk if its possible to reduce detection radius other than through the scanner item) and strikes at medium ranges? Something like a Barracuda but less SRM-boaty and more energy-focused? Maybe a HF with the energy generation and weapon slots of the underweight VHF and the survivability of less than a regular HF?

**Comment by IrateRedKite** [comment]
I quite like the idea of an underweight VHF, and we can spin it as a sort of high-tech variant of the standard Defender with the trade off being price and mass.

Stealth as a mechanic doesn't really exist at the moment, but we could reasonably give it better scanners with very little effort
