### ISSUE TITLE
Select a helmet/spacesuit combo for a new default MP player character model to replace Trent with

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#77]

**Comment by FJonske** [comment]
Strong vote for the helmet that's on the logo and game icon. It's *the* FL helmet, as far as I'm concerned. Even if it is a Liberty-specific one, we *are* in Liberty.

Now, if a player can modify this, that'd be sick. But yeah, out of scope, probably.

**Comment by IrateRedKite** [comment]
Closing as a duplicate of https://github.com/better-modernized-combat/bmod-client/issues/116
