### ISSUE TITLE
Missiles doing too much damage again?

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#86]
After I added the Xenos wreck field with wrecked civilian line fighters back in NE of Cheyenne, my SRMs are doing too much damage to AI again, sometimes even destroying full health fighters in one shot. Milo has suggested this might be related to the return of the wreck field, in that its confusing the IDs of the parts of those wrecks and the parts of the actual enemy fighters and its somehow making trouble with the method we used to stop the vanilla bug of too much missile damage, which was to give the other parts of a fighter enough explosion resist that they could ignore the missile damage and stop taking it multiple times at once.

Anyway, it's happening again!

**Comment by IrateRedKite** [comment]
This should be fixed as of 7fd933c39496971617bc919ebef862d6f2914a2a, but you mentioned not being able to reproduce before the fix was deployed! I'm going to close this for now, but if it crops up again, please re-open this issue. <3
